# Generated by Django 5.0.3 on 2024-04-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='province',
            new_name='city',
        ),
    ]
